### PR TITLE
形容詞接頭辞 into PART

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
イ形容詞接頭辞 and ナ形容詞接頭辞 should have been `PART` not `NOUN`.

### CODE REVIEW

**Comment by KoichiYasuoka** [comment]
May I add a test "超重くて不完全" in `test_dependency_parser.py`?

**Comment by tamuhey** [comment]
> May I add a test "超重くて不完全" in test_dependency_parser.py?

Yes, thanks!

**Comment by KoichiYasuoka** [comment]
It's OK!
deplacy

**Comment by tamuhey** [comment]
Thank you so much, @KoichiYasuoka san!

**Pull request merged**
